### ISSUE TITLE
module not found - cant resolve 'fs'

### ISSUE THREAD

**Issue by journaux** [foxglove/wasm-bz2#8]
**Description**
![image](https://github.com/foxglove/wasm-bz2/assets/98918683/ee3335b6-d5f6-47f7-b6ef-fd5c68faa8e7)

- Version: latest
- Platform: linux/browser/next.js

**Steps To Reproduce**
npm install, try to run @mcap/browser trivial example

**Expected Behavior**
no errors

**Comment by jtbandes** [comment]
This is due to the wasm module produced by emscripten which tries to access `fs`. You can fix it by stubbing out `fs` in your bundler, e.g. for webpack: https://stackoverflow.com/a/68098547/23649

**Comment by defunctzombie** [comment]
Closing as resolved by Jacob's comment.
